var Quotation= new Array()
Quotation[0]  = "<div id=\"qotesTex\"><div class=\"quoteCon\" ><div class=\"quotes\"> </div><div class=\"quotesJudul\">*** Ada Kalian ***</div><div class=\"clear\"></div><div class=\"quoteConSub\" >Kadang naik kadang turun, kadang semangat kadang <i>tired</i>. Sesekali atau sering saya jumpai kalian, terimakasih telah ada. Terimakasih sedikan tempat beristirahat, disaat apapun suasananya, disaat bahkan kalian tak sadari itu.</div><div class=\"clear\"></div>";
Quotation[1]  = "<div id=\"qotesTex\"><div class=\"quoteCon\" ><div class=\"quotes\"> </div><div class=\"quotesJudul\">*** Ingat aku ya :) ***</div><div class=\"clear\"></div><div class=\"quoteConSub\" >Mohon maaf apabila sering menyinggung, ngegas dan lain sebagainnya. Semoga ada kenangan baik selama ini, barangkali senda gurau/berbagi cerita/susah bareng/apapun itu dapat menjadi ingatan yang memberikan hal positif untuk mu.</div><div class=\"clear\"></div>";
Quotation[2]  = "<div id=\"qotesTex\"><div class=\"quoteCon\" ><div class=\"quotes\"> </div><div class=\"quotesJudul\">*** <i>Learn is not only math, but life</i> ***</div><div class=\"clear\"></div><div class=\"quoteConSub\" > ^^ thanks kawan, saya sedikit belajar bagaimana bahwa hidup itu tidak sekedar mengalir tanpa melakukan apapun. Mengalir perlu, tapi memperhatikan segala sesuatu yang dilalui juga perlu. Sosial bukan berarti <i>take and give</i> saja, tapi bagaimana saya berkomunikasi* dengan sekitar.</div><div class=\"clear\"></div>";
Quotation[3]  = "<div id=\"qotesTex\"><div class=\"quoteCon\" ><div class=\"quotes\"> </div><div class=\"quotesJudul\">*** <i>About 5 years</i> ***</div><div class=\"clear\"></div><div class=\"quoteConSub\" > Bila laki laki mampu berbicara 2000 kata per hari atau bahkan bila perempuan mampu berbicara 7000 kata per hari, maka aku tak tahu sudah berapa banyak ilmu/pelajaran/pengalaman/cerita/hal bermakna lainnya selama hampir 5 tahun atau lebih. <i>I just can say thank you very much, without you I can't do anything what I want</i>.</div><div class=\"clear\"></div>";
Quotation[4]  = "<div id=\"qotesTex\"><div class=\"quoteCon\" ><div class=\"quotes\"> </div><div class=\"quotesJudul\">***  ***</div><div class=\"clear\"></div><div class=\"quoteConSub\" > .. </div><div class=\"clear\"></div>";

var Q = Quotation.length;
var whichQuotation=Math.round(Math.random()*(Q-1));
function showQuotation(){document.write(Quotation[whichQuotation]);}
showQuotation();